<template>
  <div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <div>回到顶部测试</div>
    <ms-back-top>test</ms-back-top>
  </div>
</template>
<script>
export default {
  name: 'MsBackTopExample'
};
</script>
